-- Rename the 60 weapons to match the new sprite art (by sort_order; starter untouched).
update store_items as s set name = v.nm
from (values
  (11, 'Thornwood Branch'),
  (12, 'Crossguard Blade'),
  (13, 'Broadsword'),
  (14, 'Footman''s Sword'),
  (15, 'Worn Falchion'),
  (16, 'Hooked Saber'),
  (17, 'Bronze Cleaver'),
  (18, 'Cinderbrand'),
  (19, 'Twin Ember Blade'),
  (20, 'Heavy Cleaver'),
  (21, 'Horned Blade'),
  (22, 'Venom Fang'),
  (23, 'Boneguard Saber'),
  (24, 'Scimitar'),
  (25, 'Estoc'),
  (26, 'Bramble Staff'),
  (27, 'Rusted Brand'),
  (28, 'Minstrel''s Edge'),
  (29, 'Rapier'),
  (30, 'Jade Kris'),
  (31, 'Beastfang Sword'),
  (32, 'Gore Sawblade'),
  (33, 'Heavy Crossbow'),
  (34, 'Bloodletter'),
  (35, 'Cinderroot Blade'),
  (36, 'Coiled Pike'),
  (37, 'Wildfire Brand'),
  (38, 'Sunspear'),
  (39, 'Glacial Greatsword'),
  (40, 'Reaper''s Khopesh'),
  (41, 'Sugarcone Lance'),
  (42, 'Tinker''s Multitool'),
  (43, 'Emberchain Whip'),
  (44, 'Ripsaw Blade'),
  (45, 'Glasspane Greatblade'),
  (46, 'Maestro''s Warbow'),
  (47, 'Warden''s Glaive'),
  (48, 'Tidecaller Trident'),
  (49, 'Solar Halberd'),
  (50, 'Searing Estoc'),
  (51, 'Phoenix Plume'),
  (52, 'Gilded Falcon Blade'),
  (53, 'Thornspark Lance'),
  (54, 'Infernal Greatsword'),
  (55, 'Starfall Edge'),
  (56, 'Zephyr Saber'),
  (57, 'Moltenscar'),
  (58, 'Verdant Thornblade'),
  (59, 'Thunderbrand'),
  (60, 'Eye of the Grove'),
  (61, 'Glacial Maul'),
  (62, 'Tempest Edge'),
  (63, 'Emerald Greatblade'),
  (64, 'Sakura Greatblade'),
  (65, 'Azure Lightblade'),
  (66, 'Rose Rapier'),
  (67, 'Crystalsong Blade'),
  (68, 'Dragoncoil Blade'),
  (69, 'Dawnbreaker'),
  (70, 'Abyssal Edge')
) as v(so, nm)
where s.item_type='weapon' and s.sort_order = v.so;
